version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:latest

commands:
  yarn-install:
    steps:
      - restore_cache:
          key: yarn-cache-{{ checksum "package.json" }}
      - run:
          name: install yarn
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "package.json" }}
          paths:
              - node_modules