import React, { Component, PropTypes } from "react"

export default class Main extends Component {

 	render() {
		const{ state, talknAPI } = this.props;
    const { app, user, style } = state;
		return (
      <main style={ style.main.self }>
        <header style={ style.main.header }>
        </header>
        <ol style={ style.main.body }>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
          <li>
            投稿
          </li>
        </ol>
      </main>
		);
 	}
}
